// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorPedidos.Infrastructure.Persistence;

#nullable disable

namespace MonitorPedidos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529160655_AddIncidentUpdatedAt")]
    partial class AddIncidentUpdatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitorPedidos.Domain.Dashboard.BrandSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_at");

                    b.Property<int>("PendingCountCurrent")
                        .HasColumnType("int")
                        .HasColumnName("pending_count_current");

                    b.Property<int?>("PendingCountPrevious")
                        .HasColumnType("int")
                        .HasColumnName("pending_count_previous");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("site");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Site", "CheckedAt")
                        .HasDatabaseName("IX_brand_snapshots_Site_CheckedAt");

                    b.ToTable("brand_snapshots", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CloseType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClosedByRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ComentarioResolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCandidatoReglaNueva")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RetryMetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("retry_metadata");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Module")
                        .IsUnique()
                        .HasDatabaseName("IX_incidents_Module_Open")
                        .HasFilter("[ClosedAt] IS NULL");

                    b.HasIndex("OpenedAt")
                        .HasDatabaseName("IX_incidents_OpenedAt");

                    b.HasIndex("Module", "ClosedAt")
                        .HasDatabaseName("IX_incidents_Module_ClosedAt");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Rules.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppliesTo", "IsActive")
                        .HasDatabaseName("IX_rules_Module_Active");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Rules.RuleHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("author_user_id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("changed_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rule_id");

                    b.Property<string>("SnapshotAfter")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_after");

                    b.Property<string>("SnapshotBefore")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_before");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("IX_rule_history_ChangedAt");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("IX_rule_history_RuleId");

                    b.ToTable("rule_history", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Simulation.SimulatedJobStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("LastRunAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobName")
                        .IsUnique()
                        .HasDatabaseName("UX_simulated_job_statuses_job_name");

                    b.ToTable("simulated_job_statuses", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Simulation.SimulatedOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFailure")
                        .HasColumnType("bit")
                        .HasColumnName("is_failure");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("site");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_simulated_orders_created_at");

                    b.ToTable("simulated_orders", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Incidents.Incident", b =>
                {
                    b.OwnsOne("MonitorPedidos.Domain.Alerts.AlertMessage", "Alert", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AccionSugerida")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Alert_AccionSugerida");

                            b1.Property<string>("CausaProbable")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Alert_CausaProbable");

                            b1.Property<DateTimeOffset>("Cuando")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Alert_Cuando");

                            b1.Property<string>("Donde")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Alert_Donde");

                            b1.Property<string>("QuePaso")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Alert_QuePaso");

                            b1.Property<string>("SeveridadTexto")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Alert_SeveridadTexto");

                            b1.HasKey("IncidentId");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.Navigation("Alert")
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Rules.RuleHistoryEntry", b =>
                {
                    b.HasOne("MonitorPedidos.Domain.Rules.Rule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
