// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorPedidos.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonitorPedidos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528003426_AddBrandSnapshots")]
    partial class AddBrandSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonitorPedidos.Domain.Dashboard.BrandSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<int>("PendingCountCurrent")
                        .HasColumnType("integer")
                        .HasColumnName("pending_count_current");

                    b.Property<int>("PendingCountPrevious")
                        .HasColumnType("integer")
                        .HasColumnName("pending_count_previous");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("site");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Site")
                        .IsUnique()
                        .HasDatabaseName("IX_brand_snapshots_Site");

                    b.ToTable("brand_snapshots", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CloseType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ComentarioResolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCandidatoReglaNueva")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetryMetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("retry_metadata");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Module")
                        .IsUnique()
                        .HasDatabaseName("IX_incidents_Module_Open")
                        .HasFilter("\"ClosedAt\" IS NULL");

                    b.HasIndex("OpenedAt")
                        .HasDatabaseName("IX_incidents_OpenedAt");

                    b.HasIndex("Module", "ClosedAt")
                        .HasDatabaseName("IX_incidents_Module_ClosedAt");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Rules.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppliesTo", "IsActive")
                        .HasDatabaseName("IX_rules_Module_Active");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Rules.RuleHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author_user_id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("SnapshotAfter")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_after");

                    b.Property<string>("SnapshotBefore")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_before");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("IX_rule_history_ChangedAt");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("IX_rule_history_RuleId");

                    b.ToTable("rule_history", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Incidents.Incident", b =>
                {
                    b.OwnsOne("MonitorPedidos.Domain.Alerts.AlertMessage", "Alert", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccionSugerida")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Alert_AccionSugerida");

                            b1.Property<string>("CausaProbable")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Alert_CausaProbable");

                            b1.Property<DateTimeOffset>("Cuando")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Alert_Cuando");

                            b1.Property<string>("Donde")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Alert_Donde");

                            b1.Property<string>("QuePaso")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Alert_QuePaso");

                            b1.Property<string>("SeveridadTexto")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Alert_SeveridadTexto");

                            b1.HasKey("IncidentId");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.Navigation("Alert")
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Rules.RuleHistoryEntry", b =>
                {
                    b.HasOne("MonitorPedidos.Domain.Rules.Rule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
