// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorPedidos.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonitorPedidos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527190352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonitorPedidos.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CloseType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ComentarioResolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCandidatoReglaNueva")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Module")
                        .IsUnique()
                        .HasDatabaseName("IX_incidents_Module_Open")
                        .HasFilter("\"ClosedAt\" IS NULL");

                    b.HasIndex("OpenedAt")
                        .HasDatabaseName("IX_incidents_OpenedAt");

                    b.HasIndex("Module", "ClosedAt")
                        .HasDatabaseName("IX_incidents_Module_ClosedAt");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("MonitorPedidos.Domain.Incidents.Incident", b =>
                {
                    b.OwnsOne("MonitorPedidos.Domain.Alerts.AlertMessage", "Alert", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccionSugerida")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Alert_AccionSugerida");

                            b1.Property<string>("CausaProbable")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Alert_CausaProbable");

                            b1.Property<DateTimeOffset>("Cuando")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Alert_Cuando");

                            b1.Property<string>("Donde")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Alert_Donde");

                            b1.Property<string>("QuePaso")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Alert_QuePaso");

                            b1.Property<string>("SeveridadTexto")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Alert_SeveridadTexto");

                            b1.HasKey("IncidentId");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.Navigation("Alert")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
